# Generated by Django 3.1 on 2020-08-28 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exampleApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='subcategoria',
        ),
    ]
